### ISSUE TITLE
Orange rectangle is solid under imagmagick and inkscape

### ISSUE THREAD

**Issue by markfirmware** [ziglang/logo#1]
I’m trying to convert to .bmp to display in the andrewrk/clashos frame buffer but the orange rectangle part comes out solid orange without any white (or is it transparent?) parts.

**Comment by andrewrk** [comment]
Which one? The icon or the main one?

**Comment by markfirmware** [comment]
Actually both of them. They both display as expected in Firefox. What tool do you use to work on them?

**Comment by andrewrk** [comment]
I hired someone using 99designs for the main one. @jayschwa made the icon one based off the main one, I believe by using a text editor and a web browser.

**Comment by lnyaa** [comment]
Leaving a note here that the icon svg does open without problems on GIMP, so you can use it to get a bmp instead of imagemagick/inkscape.

**Comment by markfirmware** [comment]
Thanks for the help - gimp does work!
