### ISSUE TITLE
Consider trademarking zig and the zig logo

### ISSUE THREAD

**Issue by momumi** [ziglang/logo#4]
[FOSSmarks](http://fossmarks.org/) has a good overview of why you would want a trademark for an open source project. Some examples:

* Helps prevent forks from appearing as official versions of zig.
* If someone sells merchandise using the zig logo, you can prevent them from presenting it as an officially endorsed product.
* Prevents some else from taking the trademark and/or filing a trademark complaint against you.

**Comment by lukeholder** [comment]
Was the change in 608770bf7303613c18a8c3faf284516fa31072f0 an attempt to solve this ticket?

**Comment by andrewrk** [comment]
Nope, different issue

**Comment by andrewrk** [comment]
out of scope for this repo
